# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='orderid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productcode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='addressline1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='orders',
            name='availability',
            field=models.BooleanField(db_column='Availability', default=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, db_column='Status', default='CREATED', max_length=45),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(db_column='Availability', default=True),
        ),
    ]
