# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160715_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='dateoforder',
        ),
    ]
