# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_orders_dateoforder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='dataoforder',
        ),
    ]
